In [3]:
import pandas as pd

In [5]:
cols = ['Id','Datetime','Latitude','Longitude']
df = pd.read_csv('./1.txt',names=cols,header=None)

In [6]:
df.head()

   Id             Datetime   Latitude  Longitude
0   1  2008-02-02 15:36:08  116.51172   39.92123
1   1  2008-02-02 15:46:08  116.51135   39.93883
2   1  2008-02-02 15:46:08  116.51135   39.93883
3   1  2008-02-02 15:56:08  116.51627   39.91034
4   1  2008-02-02 16:06:08  116.47186   39.91248

In [7]:
df.shape

(588, 4)

In [8]:
from datetime import datetime
now = datetime.now()
timestamp = datetime.timestamp(now)
print("timestamp =", timestamp)

timestamp = 1580289745.00088

In [9]:
str = df['Datetime'][0]

In [10]:
print(str)

2008-02-02 15:36:08

In [11]:
date_time_obj = datetime.strptime(str, '%Y-%m-%d %H:%M:%S')

In [12]:
print(date_time_obj)

2008-02-02 15:36:08

In [13]:
ts = datetime.timestamp(date_time_obj)

In [14]:
print(ts)

1201946768.0

In [15]:
df.Datetime.dtype

dtype('O')

In [16]:
df['Datetime'] =  pd.to_datetime(df['Datetime'], format='%Y-%m-%d %H:%M:%S')

In [17]:
df.Datetime.dtype

dtype('<M8[ns]')

In [18]:
df['Datetime'][0]

Timestamp('2008-02-02 15:36:08')

In [19]:
print(datetime.timestamp(df['Datetime'][0]))

1201946768.0

In [20]:
df.head()

   Id            Datetime   Latitude  Longitude
0   1 2008-02-02 15:36:08  116.51172   39.92123
1   1 2008-02-02 15:46:08  116.51135   39.93883
2   1 2008-02-02 15:46:08  116.51135   39.93883
3   1 2008-02-02 15:56:08  116.51627   39.91034
4   1 2008-02-02 16:06:08  116.47186   39.91248

In [21]:
df['Timestamp']=df['Datetime']

In [22]:
df.head()

   Id            Datetime   Latitude  Longitude           Timestamp
0   1 2008-02-02 15:36:08  116.51172   39.92123 2008-02-02 15:36:08
1   1 2008-02-02 15:46:08  116.51135   39.93883 2008-02-02 15:46:08
2   1 2008-02-02 15:46:08  116.51135   39.93883 2008-02-02 15:46:08
3   1 2008-02-02 15:56:08  116.51627   39.91034 2008-02-02 15:56:08
4   1 2008-02-02 16:06:08  116.47186   39.91248 2008-02-02 16:06:08

In [23]:
def function(row):
    return datetime.timestamp(row['Timestamp'])

In [24]:
df['Timestamp'] = df.apply(function,axis=1)

In [25]:
df.head()

   Id            Datetime   Latitude  Longitude     Timestamp
0   1 2008-02-02 15:36:08  116.51172   39.92123  1.201947e+09
1   1 2008-02-02 15:46:08  116.51135   39.93883  1.201947e+09
2   1 2008-02-02 15:46:08  116.51135   39.93883  1.201947e+09
3   1 2008-02-02 15:56:08  116.51627   39.91034  1.201948e+09
4   1 2008-02-02 16:06:08  116.47186   39.91248  1.201949e+09

In [26]:
df.drop('Datetime',axis=1)

     Id   Latitude  Longitude     Timestamp
0     1  116.51172   39.92123  1.201947e+09
1     1  116.51135   39.93883  1.201947e+09
2     1  116.51135   39.93883  1.201947e+09
3     1  116.51627   39.91034  1.201948e+09
4     1  116.47186   39.91248  1.201949e+09
5     1  116.47217   39.92498  1.201949e+09
6     1  116.47179   39.90718  1.201950e+09
7     1  116.45617   39.90531  1.201950e+09
8     1  116.47191   39.90577  1.201952e+09
9     1  116.50661   39.91450  1.201952e+09
10    1  116.49625   39.91460  1.201964e+09
11    1  116.50962   39.91071  1.201965e+09
12    1  116.52231   39.91588  1.201966e+09
13    1  116.52231   39.91588  1.201966e+09
14    1  116.56444   39.91445  1.201966e+09
15    1  116.59512   39.90798  1.201967e+09
16    1  116.65522   39.86220  1.201968e+09
17    1  116.69164   39.85165  1.201969e+09
18    1  116.69167   39.85166  1.201969e+09
19    1  116.69168   39.85168  1.201970e+09
20    1  116.69168   39.85167  1.201971e+09
21    1  116.69167   39.85169  1.201972e+09
22    1  116.69167   39.85172  1.201972e+09
23    1  116.69167   39.85174  1.201973e+09
24    1  116.69167   39.85175  1.201973e+09
25    1  116.69167   39.85176  1.201974e+09
26    1  116.69172   39.85208  1.201975e+09
27    1  116.69172   39.85208  1.201975e+09
28    1  116.69172   39.85199  1.201975e+09
29    1  116.69171   39.85196  1.201976e+09
..   ..        ...        ...           ...
558   1  116.69158   39.85165  1.202437e+09
559   1  116.69163   39.85169  1.202437e+09
560   1  116.69154   39.85173  1.202438e+09
561   1  116.69154   39.85175  1.202439e+09
562   1  116.69159   39.85167  1.202439e+09
563   1  116.69163   39.85141  1.202440e+09
564   1  116.69162   39.85161  1.202440e+09
565   1  116.69160   39.85161  1.202441e+09
566   1  116.69154   39.85188  1.202442e+09
567   1  116.69158   39.85197  1.202442e+09
568   1  116.69158   39.85187  1.202443e+09
569   1  116.69159   39.85183  1.202443e+09
570   1  116.69162   39.85147  1.202444e+09
571   1  116.69156   39.85158  1.202445e+09
572   1  116.69155   39.85164  1.202445e+09
573   1  116.69153   39.85165  1.202446e+09
574   1  116.69153   39.85166  1.202446e+09
575   1  116.66179   39.88372  1.202447e+09
576   1  116.60394   39.90741  1.202448e+09
577   1  116.54559   39.91474  1.202448e+09
578   1  116.52195   39.91600  1.202461e+09
579   1  116.48503   39.91422  1.202461e+09
580   1  116.44460   39.92156  1.202462e+09
581   1  116.40047   39.92594  1.202462e+09
582   1  116.44152   39.93236  1.202463e+09
583   1  116.48347   39.91954  1.202464e+09
584   1  116.50789   39.93128  1.202464e+09
585   1  116.53174   39.91536  1.202465e+09
586   1  116.57156   39.90263  1.202465e+09
587   1  116.54723   39.90841  1.202466e+09

[588 rows x 4 columns]

In [27]:
print(df.shape[0])

588

In [32]:
n=df.shape[0]
eRad=6371000

In [45]:
import math
import numpy as np
import sys

In [46]:
print(df['Latitude'][1])

116.51135

In [71]:
dist=[]
speed=[]
for i in range (1,n):
    var = math.sin((df['Latitude'][i]-df['Latitude'][i-1])/2)**2+math.cos(df['Latitude'][i])*math.cos(df['Latitude'][i-1])*math.sin((df['Latitude'][i]-df['Latitude'][i-1])/2)**2
    dtime = (df['Timestamp'][i]-df['Timestamp'][i-1])
    if(dtime==0):
        continue
    dist.append(np.float64(2*eRad*math.atan2(math.sqrt(var),math.sqrt(1-var))))
    speed.append(dist[-1]/dtime)

In [72]:
angle=[]
for i in range (1,n):
    deltaL=df['Longitude'][i]-df['Longitude'][i-1]
    phi2=df['Latitude'][i]
    phi1=df['Latitude'][i-1]
    angle.append(math.atan2(math.sin(deltaL)*math.cos(phi2),math.cos(phi1)*math.sin(phi2)-math.sin(phi1)*math.cos(phi2)*math.cos(deltaL)))

In [73]:
print(speed)

[5.454515762080102, 72.50798751006703, 656.1485590246948, 4.592632417688552, 5.629701187156661, 231.6191567820539, 96.18007312731834, 513.0034221991995, 7.640134390195825, 197.65283082069632, 186.96202097745393, 618.243093193264, 447.6406775643955, 434.8953005019453, 522.0899350600503, 0.42840704375658817, 0.07146041373073236, 0.0, 0.1428017267719135, 0.0, 0.0, 0.0, 0.0, 0.7140055275270448, 0.0, 0.1428004839974683, 0.0, 0.0, 0.14280079520673292, 0.0, 0.2856025215822327, 0.571203800771606, 0.5711988316841087, 1.142402632350263, 0.28560376391751796, 0.09525458808702994, 0.42840704375658817, 0.0, 0.6149303153410833, 0.4716315497545878, 0.07134063646973102, 0.1428004839974683, 0.14303919386317154, 0.856811292061314, 1.2852379002113943, 0.42841542826795004, 0.28560997492799123, 0.7140226086192607, 0.7140226086192607, 0.5712187077295134, 2.8560190011910453, 0.14279799939982177, 0.428395861633973, 0.14279893091189355, 2.860805645593394, 0.7140210559498902, 0.0, 0.14280358995536774, 3.279103096645624, 2.5705456615580005, 3.8622933628717577, 6.14070120924318, 0.49980495637041644, 0.5712075280136939, 0.7140101864873036, 0.2856062484549034, 0.14280358995536774, 1.6422019948874829, 2.7131914943293896, 0.3573020685217386, 0.07140039760336646, 0.28560190080380654, 0.0, 0.0, 0.0, 0.4284023847963322, 0.2856012792025537, 0.14280079520673292, 0.8553837891294133, 0.2860811872501979, 1.5708394904649605, 0.1428051426247367, 18.276492084321838, 478.5273231261144, 607.0611852682559, 568.2847857840296, 523.5430541520615, 386.9478410370728, 283.3439262752765, 897.0545876072588, 211.31730706655878, 70.66687799540163, 48.00205108725709, 600.1148503987301, 167.26835513825313, 293.43198917790784, 509.13754912184737, 21.845904852260684, 0.14280731653462028, 0.2856137010014601, 0.28561245902137566, 0.1428057640595112, 0.0, 0.0, 0.1428054533448985, 0.0, 0.7128423010481046, 1.1424448679477508, 0.0, 0.14280405607363547, 0.4284098384053301, 0.7128299006934078, 0.428411702097698, 0.28608429802330787, 0.0, 0.14280390090621486, 0.14280390090621486, 0.0, 0.0, 0.42841077046277454, 0.5702645407942724, 0.14304292645105818, 0.28513351029753337, 0.14280390090621486, 0.28608367568764664, 0.14280296884877064, 0.42840704375658817, 0.9996055644507912, 1.7107675769966306, 0.0, 0.0, 0.0, 0.0, 0.428411702097698, 0.428411702097698, 0.0, 0.999616434884555, 0.0, 0.8568131553113661, 0.0, 0.14256535991557803, 0.0, 0.0, 0.14280296884877064, 0.0, 0.14280327960777978, 0.0, 0.14280358995536774, 0.14304230474746063, 0.0, 0.0, 0.14280390090621486, 0.28560811214727094, 1.7136300374154412, 0.7140070806768297, 0.2856050066142781, 0.5712137393016631, 0.5712187077295134, 0.1428054533448985, 0.8568392405626395, 0.14304572607808375, 2.856205308194817, 1.5709282866871497, 2.427724374351143, 0.0, 2.713344905323539, 3.0039602378778163, 0.2856074908599357, 0.14280358995536774, 0.14280358995536774, 1.4256737518435598, 1.8564587813822118, 0.5721661070639699, 0.28560686956150055, 0.14280327960777978, 0.14280327960777978, 0.0, 0.0, 0.0, 0.5712149816955961, 0.4276988706466203, 0.14304168241179943, 0.14256567015751723, 0.0, 309.5402718225586, 564.152986400716, 769.1101605889054, 586.4164581673042, 433.8908359434543, 14.894617464733889, 13.224250239775799, 541.4004489256644, 73.24063163026598, 126.80406285971767, 1.4304121570710946, 0.14304292645105818, 0.5712162236614566, 0.14280358995536774, 0.07134249837113149, 0.2856087328146959, 0.14304323770106964, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7140288190192391, 0.2856137010014601, 0.7140396861507093, 0.5717063078790979, 1.4256706517548756, 0.42841077046277454, 2.4316768666872868, 1.5708053269572446, 0.570260820355412, 0.14280358995536774, 0.7152146330076067, 1.2852351053565698, 1.5708463225963059, 0.42841636002256034, 1.5682223706610205, 0.9285708691979616, 1.1423578974869744, 0.5711864056868395, 2.2847953229676494, 0.42912318075937295, 0.0, 0.4284121677664833, 0.28513537035073744, 0.1428057640595112, 0.07146258923757556, 0.14280607415975516, 0.0, 0.14256815047538557, 0.28561183821762, 0.42913251241159833, 6.140914793747945, 4.284419696944968, 3.5701363245160604, 0.4284033167840231, 1.2852183355845779, 2.284894702890306, 1.428068505130692, 0.2860867862383885, 0.0, 0.14304292645105818, 0.2851341303263503, 0.1428048323049012, 0.2860855420514483, 0.14280390090621486, 0.14280358995536774, 0.0, 0.0, 0.0, 1.1443446569685969, 0.1428057640595112, 0.0, 0.1428054533448985, 0.0, 0.1428051426247367, 0.42841356511465695, 0.14280421124270296, 58.3809305511834, 702.7321184448622, 678.0144444716011, 682.4621339212357, 787.1522272302013, 635.0700586171995, 309.1602463997067, 409.14556994245265, 24.129214683054716, 366.33064087222556, 141.00409005497542, 196.57837504208138, 607.9402161800933, 15.866463549171579, 792.2487139244935, 254.04765240652267, 801.8029306093686, 316.84894044265747, 203.95626382074678, 277.6031564332139, 185.8242438502515, 41.52351648970257, 164.24050726339053, 366.7737555571282, 205.94441205948021, 432.01387623975137, 53.850029226230596, 47.320133069450065, 10.882944950950295, 179.44799290015484, 285.7136768176831, 293.86513888738637, 80.13244076106847, 297.25263599909186, 122.46362544046815, 478.1034442344315, 10.330057243986479, 140.6893464930577, 0.0, 0.0, 0.1428054533448985, 0.1428051426247367, 0.0, 0.142567220271116, 0.14280452157363974, 0.0, 0.0, 0.0, 0.0, 0.14280421124270296, 0.0, 3.5700043360273277, 2.4316345533690207, 3.7067678673021622, 0.8568466915446596, 0.1428057640595112, 0.14304417101119654, 0.14280607415975516, 0.28561308001696817, 1.5708377805267453, 1.2830742879790924, 0.14280296884877064, 0.14304137113399398, 0.21420352187829408, 0.28560438527144755, 0.28560562733720585, 0.14280327960777978, 0.0, 0.0, 1.1424374158736492, 0.7152177434471673, 0.42770166039603097, 0.1428051426247367, 0.4291287797475696, 0.14280390090621486, 0.14280358995536774, 0.0, 0.1425659799887199, 0.856828061939459, 0.5721785491366449, 0.14280669515534763, 2.284944379429577, 1.999330678796795, 1.0710711705738434, 3.141784859209662, 0.28561059596798866, 0.0, 0.0, 0.1428054533448985, 0.28560997492799123, 0.14304292645105818, 0.0, 1.5708668167133337, 1.5708668167133337, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5712199498317097, 0.2853721647785394, 0.0, 0.14280452157363974, 0.1428048323049012, 419.3754290039042, 878.999569175202, 844.6499044005596, 30.474474525254735, 12.16696425472151, 1.7776359418582888, 157.36937190911397, 854.6222657845465, 1001.013559629549, 836.8884609093019, 770.5480145928639, 245.8408202592704, 0.14795170776553065, 0.4438540504070524, 4.2905060962685635, 424.4271184812786, 0.5139250116120653, 5.906669799708684, 109.88580037279995, 136.29136103615, 0.0, 2.431687444071928, 4.998169107383589, 4.712569693736118, 1.142410086694947, 0.5712075280136939, 1.1424001472769918, 0.7128097463356305, 1.4279877591089962, 0.42839027028257265, 3.8620498174257496, 0.2856087328146959, 0.42841077046277454, 0.28560562733720585, 2.142072482062594, 3.4272824290128074, 1.287355542188764, 1.3555222027041431, 5.426943399242483, 4.14165520793723, 3.2900588408774194, 0.42841356511465695, 1.5708360746121222, 2.1420585082411128, 0.42770445080623526, 0.5721723282766412, 0.2856074908599357, 1.856418408731746, 1.7136151292524562, 0.7854077883962832, 1.5682019069476536, 2.28862460673728, 0.14279830984175176, 0.8567963834417242, 1.7164871220402536, 8.981070507443722, 8.438890047988638, 0.14256535991557803, 0.6426077699871292, 0.5721524190491907, 3.427267522726909, 1.7136561230205856, 0.0, 0.28513103007145096, 1.5708189934175456, 0.8582248941067399, 2.142007263741641, 0.0, 0.9996120872334509, 0.8568094287779623, 0.1428026584900823, 1.5708497382659943, 1.999256781642138, 0.5712124970928302, 0.0, 0.28560935387689423, 2.145615901342375, 3.5701052719606916, 2.570495361813795, 0.5712075280136939, 0.2851266896543826, 0.5002228960300839, 0.14280296884877064, 0.42841077046277454, 3.5700043360273277, 453.75599504552173, 902.4194079180673, 722.094222753566, 954.3904262743198, 38.684417362850766, 427.99754685331357, 22.88726233682583, 7.705525049213089, 481.38992868300835, 724.6238398606941, 506.2207191755965, 779.0322333036438, 518.5059011367157, 0.5721773052530558, 3.5700353955943287, 0.2855956881475881, 1.1423951772001977, 2.138480399468331, 0.28560997492799123, 0.0, 0.2856087328146959, 0.5712137393016631, 0.4284098384053301, 0.28560811214727094, 1.1424249941856603, 0.1428020371472518, 0.28560376391751796, 0.2856025215822327, 0.9996142608754927, 1.5708531542805053, 0.4284182230759476, 1.356681300877475, 0.7140536561784653, 4.5773885651100334, 1.8564264840419324, 0.5712187077295134, 0.428414496496691, 0.1425666002422991, 0.0, 0.0, 0.0, 3.8555962948549403, 4.998038672663283, 0.0, 0.2856137010014601, 0.2856137010014601, 0.0, 0.0, 0.14256908002197768, 0.14280669515534763, 0.14280669515534763, 1.4280529799632902, 0.5715250416667694, 0.7136152859085316, 0.14304323770106964, 0.1428051426247367, 0.0, 0.14256784027776886, 1.1424349314219118, 1.4304308208759269, 0.5712224341724366, 2.856037636184072, 0.5711975885957566, 1.142410086694947, 0.28560562733720585, 0.8582435612467774, 2.1419839672549013, 11.710365133449965, 4.998581966093982, 1.1405786768477875, 3.712921593187348, 1.1443222598024356, 0.42841077046277454, 3.284575409475957, 1.4280964469349375, 0.7128485005605082, 0.28609051853234735, 0.2856137010014601, 0.28561245902137566, 0.7140334765278235, 1.8564708919733808, 0.428411702097698, 0.14280452157363974, 0.7152115224568621, 1.2852406954221431, 0.0, 0.7140257138747553, 0.5702645407942724, 0.14280327960777978, 0.28608429802330787, 0.8568299250927578, 0.5712211923175818, 0.0, 0.14256691005687827, 0.428411702097698, 0.8582566262603597, 0.1428054533448985, 0.28561183821762, 0.0, 426.04747480452016, 836.0132198254618, 852.010634901602, 16.806196781694286, 544.8338878735383, 598.4372567355967, 657.1066402413347, 612.3546135540241, 622.1298196433314, 360.73940485314944, 351.1926519625474, 583.6143845064936, 356.1687950873134]

In [74]:
print(angle)

[-1.5902517181798588, -0.0, 1.3894022164055144, -3.0947249867096507, -1.5438692412112762, 1.59067821771086, 3.025208951107452, -0.02842878633605359, -0.23801279022124006, -3.1322580556333657, 0.27330914304983156, -0.37277678170076045, -0.0, 0.03215834669931137, 0.19512411142033118, 0.6060094639108322, 0.254745794401629, -0.29122758399955856, -1.0633389465774694, 1.5707941395889873, -2.0782449582659304, -1.5707897653037368, -1.5707919524660858, -1.570794139630492, -1.5707941396304905, -1.39868620708096, -0.0, 1.5707766402972403, 1.9257737534638593, 1.5707657039836174, -1.5707919521062608, -3.141592653589793, -0.0, 1.6291753170351233, -1.340780380132375, -0.0, 2.920457246615128, 2.0782395507821896, -1.652923993153175, -1.2487762793630208, 1.5707328990446494, -1.0117779775300675, 1.9257653855552346, -1.7896363523876657, 1.9257737534638593, -3.141592653589793, 2.116005229736276, -2.129718445326738, 0.29123962427430783, 1.6276740882141323, -1.1927277608207336, -2.3181331670227365, -0.0, 0.8437514256516986, -0.7323502042054431, -2.4092194988613596, 2.8503767507289903, 0.7323760381250883, -2.124121169244685, 1.4680772100616915, -1.570794139856524, -2.078232563289658, -2.5282670705573795, 0.5400689834808579, -2.4471504978917187, 0.30396080399159686, 2.7737371809393245, 1.4282127270852583, -1.905216646841944, -1.989311526054832, -1.9257579024981406, -0.7102977472850086, 2.234761100040239, -0.34528522330451794, -1.215807360091534, -2.4091943316106197, 1.570789765034131, 1.5707919522877192, 1.5707919522877192, 1.5100926903660659, -1.6529263737985558, -1.535988582497588, -2.015510014220647, 1.2158079341062564, 2.9010765122460414, -0.732424408835183, 0.028078067433756456, -2.3899680287629597, -2.723388721463667, -2.9678174107526014, -3.0872114924353866, 2.926692963803361, 3.0354465846605443, 3.1210064942923577, 1.1259615744216307, -1.0360140826371276, -0.20149012842400826, 0.12800876548729376, -0.0, -0.3221054824247566, 0.7869216050164304, 0.7281691238421923, -3.1357147460596746, -0.0, -0.4225694176311426, -0.0, -1.0633658003335151, -1.5707941401717083, -1.5707941401717083, -0.0, 1.5707941401240384, -1.7667503724277156, 1.2288817637611176, 1.5707832059703055, -0.0, -1.503432064884953, 1.3519228696163572, 2.0782150680579954, -0.8756554309129247, 2.4091725660521965, -1.5707897662473032, -1.2158232138323353, -2.4091735444251867, -1.5707919530965007, -0.0, -0.0, -1.3368409269465653, 1.7702414862894995, -0.0, -2.078226366656356, -0.7324161767617317, 1.3519468002569854, -0.73240892200233, 0.7324074819331005, 0.7323982699469165, 0.12776033540950993, 2.4984715269538076, -1.570794139856524, 1.570791952915066, -0.0, -1.570789765977723, -1.693669939129872, 1.0633446604028547, 1.5707832051605441, -0.47466649456947674, 1.570778828764628, 2.044955335363164, -1.5707788309234836, -0.7324074819331005, -1.5707941397673486, -0.0, 2.4091807976435184, -0.0, -2.4091783800784365, -0.0, -3.141592653589793, -3.141592653589793, -1.570794139945698, -0.0, -0.7324147350696874, 1.622377110011458, -1.2697930911483488, 1.9749312165006105, -2.409182239307332, -2.548211105215625, -2.9204448615185474, -2.4091614542306625, -2.9928118941963544, -1.485441600507818, -2.4888616210621723, 0.31607664242469646, 0.976911590682241, -1.570787579759419, -0.0, -2.625009355734933, 0.5079645284230065, -1.2158158611514798, -2.409175961163238, 0.7324123185925637, 1.9051673375905063, -1.253267369168151, 2.029796636947126, -0.0, 1.8419435244792997, 1.4783663066449533, 1.5707875788599681, 1.57079195282589, 1.57079195282589, -2.4091681921899974, -1.2487835822108213, -1.5152091727888772, 2.409178380431715, 1.570765709649223, -2.320378542140204, -2.5674614337671295, -2.9912087017931364, -3.0915114081250996, 2.9528563073312752, 1.1541519531447284, -2.940684748786292, -0.0, -0.04020023462015726, 0.9081199334280509, 0.2872821002579312, -1.7774955362036913, 1.636077302744239, 1.111762447693492, 2.078232563289658, -1.9257563184485842, 2.7190334136903367, -2.40916628963207, -1.5707919533670998, -1.5707941400825423, -0.0, -0.0, -0.0, 1.719865559896117, -1.7896032637993258, -1.7601469272445742, 0.5120602981167264, 0.8234213377156673, 2.159159905372083, -1.1292050404586733, 1.9465729788898332, -2.9204511064349776, 1.9257579024981406, 1.6963964635685558, -1.3195156176997536, -2.5623758420497285, -0.7324224530596165, 0.3160378534583528, 0.4785125813493176, -2.816376251355427, -2.719076713471108, -0.0, 2.4091733799942823, -1.7540146984421798, -1.5707832048909582, 2.2659097838511437, -2.078216830388459, -2.4091590371447067, -2.0782160403466916, -1.215834309631369, -1.5707919536346007, -0.0, -2.078212700384533, 1.299624182437517, 3.0997804137461147, 0.422580644404357, -0.6911507710778334, 0.2912222321682119, -3.141592653589793, -2.441084538418026, 1.083782305562227, -1.4478263792548103, 1.5707438445759325, -1.432664974017108, -1.989302497086354, -1.0633596046099767, -0.4225548662921551, -0.7324147354229659, -0.7324123182392852, -0.0, -0.0, -1.5707941398565255, 1.5707941398565255, 2.2978084264055565, -1.2158327240179305, -1.5707897669212172, -0.0, 1.5707897667864381, 1.0633616708637899, 1.351926994954776, -1.8419397597060883, -0.2055119167031734, -2.514975454559189, -2.7976551122665665, -3.019272286639633, 3.1385164455334587, -3.0777057161414794, -2.7710743645434808, 0.2098855645851239, 1.2291005353084294, -3.0740307758360137, -0.08751697315605178, 0.15088445012529875, -0.041369361618404064, 3.0755661280270084, -0.1456978278663995, 2.756194792198878, -3.028390475629212, -2.193637487054214, 0.5227856009292673, -2.0583643177914235, -0.8778033382239895, -0.0, 1.476684254047796, 1.83767915595431, 0.05022634681054812, 2.650099360580874, -2.8865535586931537, -2.951413156559987, 1.7880086585253854, -1.5952086634229952, -2.4135201805437294, -0.09138654498290376, -1.0568171906393407, -0.5494620492309126, 0.9598976762930174, 1.841217260219183, 0.36846239672541964, 1.6628528128342601, 0.2591857082963656, -1.5707613408075578, 1.5707941401717083, -1.0633637355509353, -1.063361670712904, -0.0, -0.0, -0.0, -0.0, -0.0, 1.5707941399933705, -0.0, -0.0, 0.732417154304525, 1.5707941399456995, -0.466466637439148, 2.88302809415387, 2.3721438288104904, -0.5400755833292246, 1.4854395330953634, -1.6190548897576653, 1.6631698431806905, 1.789604293775444, -0.5791587575186418, -2.6782699149815774, 1.7540400719688343, 0.7324074819331005, -1.126041431242681, 1.740209174057889, -2.0782333535419037, -3.141592653589793, -1.5707919529150645, -1.5707941398565255, 2.2086961406033727, 0.7324156617934449, -1.892760955153662, -1.4132431248471975, -0.7324151990278526, -0.0, -0.0, -0.0, -0.0, -2.4091759615165165, 2.850348475660326, -2.920439658225242, 1.0633719974958553, -2.7667160688026655, 0.7990890410226342, -1.94871577174395, 0.7962139298796682, 1.7088735405756301, -1.5707919535454349, -1.5707941401717098, -0.7324268264214788, -0.4225585041041865, -0.0, -1.5707941399933705, -2.4562170426898957, -0.31605078561920685, 1.5707919531856729, 1.5707919531856729, -1.570794139993372, 1.570794139993372, 1.570794139993372, 2.136837217664176, 1.2411048664712827, -0.0, 1.5707919531856729, -1.6151919762279687, 1.6560975058239702, -2.477092984795331, -2.9440601832757194, -3.114632119185704, -2.0929115267337908, -1.6745946014182715, 1.563044786444117, 1.3759006551624595, 2.377887850903588, 2.932902168196089, -0.2214388178880195, -0.20118061625640501, -0.9629268875011596, 1.4972959350395267, 0.5741580373687216, -0.0, -1.534537478543207, -0.5159878921513937, -1.7171138360084017, -1.6143716955091254, 1.8808083603934846, 0.2608888702698525, -1.5706848020780864, 1.3032283779001035, -2.1951825715138535, -0.0, 0.5598300057716677, -2.409178788833398, 0.5933571515504543, -1.1328368023395339, -2.3181719650026498, -0.8233752485491862, -1.3195455185561218, 2.294125163094024, 1.371280889725694, -0.0, 1.4941916806127813, -2.3769576105008703, -0.14876269670199646, 2.356594913289648, -1.9040847323251056, 2.3472932211410336, 1.0324119406448786, -1.11360202728404, 2.850351331097066, -1.3352856772051203, 1.9748602887704476, 1.3652118274007916, 0.8437514256516986, 0.4225512277881308, -0.9203314506627973, -2.992821826013024, -0.9470270988698255, -0.0, 1.9578999238511214, -0.3252247066899741, -1.5901796558203998, 1.65820129481653, 2.9204488138577873, 0.1417420046696278, -2.3309304503174104, -2.409180797996797, 1.3731307991196056, 0.7323755221144583, 2.7506212344908176, 1.0255346683747373, -1.5707263418696293, 1.8784130269800012, -1.2431675760035656, -1.1260062768232382, 1.918576269551835, -1.570794139767347, -1.3247095607289965, 1.8927544090262287, -1.8419460345161789, -1.898254280147536, 1.32840099895396, -1.7502863731136808, -0.0, -1.593994575966543, 1.4289277174336752, -0.0, 2.3017567037324684, -1.2032477368460055, 0.8437296849933107, -0.0, 1.9595939685205763, -1.7283241879916724, 2.409171588221733, 0.574536551359301, -2.3684930757622635, -2.805509907753059, -2.9275473126323357, -3.0883212238438063, -2.836864612861761, 0.48105821599612353, -2.449994194329419, 1.5300944963989287, 0.08501825118293391, -0.05136897602094305, 0.17825200107179773, 0.3115506506100551, 0.7316116586053796, 1.328506200115519, 0.37674192692571534, -0.0, -3.141592653589793, -1.8502056448842297, 2.601510951811718, -0.7324210127947741, 1.5707919532748422, 1.4478251939484283, 0.8437417636676896, -2.850356681638003, -2.409170148153965, 1.1522264539772062, -1.7896301673768449, -1.4854059306045395, -0.4225366734846679, -3.141592653589793, 2.685542003008414, 0.540076905893779, 2.7388508878051554, -0.8995856727932137, 0.5331085410698032, -2.1521060244841044, -2.1368394187246342, -0.982419861940644, 1.5336811553826315, 1.5707919530965007, 1.5707941399456995, -1.5707853925501387, -0.9822964370436745, 2.4235114639156348, -0.0, 1.5707832078582433, -1.9892898587557095, 1.2158317120896596, 1.5707941403023684, -1.5707941403023684, -2.4091517823787294, -0.0, -3.141592653589793, -1.0412507189081983, 0.29121901600955435, 2.376977042874614, -0.0, -1.6360769868429421, 1.7283189150592069, 1.5707941401240384, -2.4091614542306625, 1.3148132798687346, -1.9368859515910477, -0.7324214756759378, -0.3452728756898616, -2.7190603352606915, 1.7949857700994885, -1.8784144303498185, 1.4769417726895802, -1.0002997157042488, -2.453069205228066, 0.2991061726650665, -0.8437815473081163, -0.3933926730369016, 2.3503798908572446, 2.601524158918367, -2.6407021822706116, 1.0633522663611144, 1.3676606205806299, -1.6936840068333296, -0.9328799971668449, -0.42256577977212223, 2.5179197911360722, -0.20461984133196023, 2.159157660069392, -1.7540357159703446, -0.0, -0.6236346205151042, -2.7613502403481562, -1.5707919536346022, 0.9634250467725809, 1.4013022307839085, -1.626296002340614, -3.141592653589793, -1.8129914504586353, -1.1117701759897907, 1.5707744592038617, 1.29963665484862, 1.4783147174317588, -2.115987979634071, -1.7540331029173661, -2.7190243197792268, -1.5707941402608732, -2.3612929351390015, -2.775460782123358, -3.0223152549452403, -3.090453006580537, 3.0948558812230633, -2.965634266385226, -3.043908771991209, -0.15204343151667826, 0.28821990217604937, -0.4337761583119674, 0.5680808699886194, 0.2933540943579972, -2.9189127572822957]